### ISSUE TITLE
About preprocess data

### ISSUE THREAD

**Issue by 1054651112** [filby89/NTUA-BEEU-eccv2020#1]
Hello, after reading your paper, I am very interested. Could you share the data after preprocessing? Due to my limited hardware, I can't use GPU to preprocess data. Looking forward to your reply!

**Comment by filby89** [comment]
Hi, thank you for your interest in our work ! Sadly, I do not have the permissions to share the preprocessed dataset, especially since it requires a consent form.

**Comment by 1054651112** [comment]
Thank you for your reply! I know that the dataset is authorized. I am currently applying for the original data set to do research, and I have submitted a consent form. What I want to ask is if I have applied for the dataset, can you share the preprocessed data?
I'm very sorry to disturb you.

**Comment by filby89** [comment]
I'm sorry but I do not have any connection with the people who released the dataset and am unable to do this on only verbal communication. However, I believe you can ask them if they can provide the preprocessed optical flow since their baseline method of TSNs also used optical flow (which is the part that requires the GPU - you can extract the RGB frames from the videos you will download without GPU computations!).

**Comment by 1054651112** [comment]
Thank you very much for the information and wish you success in your work!
